.TH "FIREGLCONTROL" "1" "2014\-01\-04" "ATI Linux driver" "Debian GNU/Linux fglrx\-driver"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
atigetsysteminfo \- generate a system configuration report
.SH "SYNOPSIS"
.HP 14
\fBamdcccle\fR
.SH "OPTIONS"
.PP
This program has no options.
.SH "AUTHOR"
.PP
Michael Gilbert <mgilbert@debian.org>
.br
